export enum InputType {
  Text = "text",
  Password = "password",
  Email = "email",
  Phone = "phone",
  Phones = "Phone",
  Numbers = "numbers",
  SearchIcon = "search icon",
  Date = "date",
  Search = "search",
  Number = "number",
  Input = "input",
  Prefix = "prefix",
  Checkbox = "checkbox",
}

export enum Placeholder {
  Text = "Insert text here",
  Password = "Password",
  Number = "Number",
  Date = "Date",
  Phone = "Phone",
  PhoneNumber = "Phone Number",
  Search = "Search",
  SearchIcon = "Search here ...",
  Email = "Enter your email",
  Input = "Enter Something",
  Prefix = "Enter Your Values",
  UserName = "Username",
  YourName = "Your name",
  YourEmail = "Your email",
  YourPassword = "Your password",
}
