export const productData: ProductData = {
    brand: "Mango",
    name: "Women Empire Dress",
    rating: 4.1,
    price: 3950,
    discount: "25% off",
    isTaxInclusive: true,
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    selectedSize: "L",
    image: "path/to/image.jpg",
    description: "302014 (Tessa Rain )",
    icon: "path/to/icon.png",
    arrival: "Get it by Thu, 6 June",
    paymentMethod: "Cash on Delivery Available",
    returnPolicy: "Easy 14 days return and exchange available",
    productCode: "00123456",
    productDetails:
      "Navy Blue printed woven empire %S, has a V-neck, three-quarter sleeves, and flared hem",
    sizeFit: "Semi-Fit\nThe model (height 5'8\") is wearing a size S",
    materialCare: "Cotton Machine-wash",
    specification: "",
    reviews: "Reviews",
    ratingsDistribution: {
      5: 20,
      4: 10,
      3: 0,
      2: 1,
      1: 0,
    },
    averageRating: 4.5,
    totalReviews: 23,
  };

  export const product: Product = {
    Taxes : "Inclusive all Taxes",
    Size : "Select Size",
    AddToBag : "Add to Bag",
    Wishlist : "Wishlist",
    Change : "Change",
    ProductCode : "Product Code :",
    ProductDetails : "Product Details",
    SizeFit : "Size & Fit",
    Material : "Material & Care",
    ProductSpec : "Product Specifications"
  }