export enum Login {
  Logo = "LOGO" ,
  Login = "Login",
  Username = "Username",
  Password = "Password",
  ForgotPassword = "  Forgot Password",
  OtherPlatform = " or login using other platforms",
  AlreadyAccount = "Already have an account?",
  Register = "Register",
  NewShopping = "Your new Shopping experience.",
  Google = " Login with Google",
  PhoneNumber = "Login with Phone Number",
  NoAccount = "Don’t have an account?",
  CreateAccount = "Create Account",
}
