export enum ProductShipmentDetails {
  title = "Shipment Details",
  womenExpireDress = "Women Expire Dress",
  size = "Size",
  exchangeAvailableTill = "Exchange/Return available till",
  dispatched = "Dispatched",
  yourPlace = "your place",
  deliveryaddress = "Delivery Address",
  shipmentMethod = "Shipping Method",
  logisticsCompany = "Logistics company",
  takingId = "Taking ID",
  orderId = "Order ID #",
  from = "From",
  to = "To",
  currentLocation = "Current location",
  kmsLeft = "kms left",
  lastStop = "Last stop",
  exchange = "Exchange",
  return = "Return",
  cancel = "Cancel",
}
