export enum Login {
  Logo = "LOGO",
  Login = "Login",
  Username = "Username",
  Password = "Password",
  ForgotPassword = "  Forgot Password",
  OtherPlatform = " or login using other platforms",
  AlreadyAccount = "Already have an account?",
  Register = "Register",
  NewShopping = "Your new Shopping experience.",
  Google = " Login with Google",
  PhoneNumber = "Login with Phone Number",
  NoAccount = "Don’t have an account?",
  CreateAccount = "Create Account",
  VerificationCode = "We’ll send you a verification code you can use to Log in",
  PhoneNum = "Phone number",
  PasswordRecovery = "Password recovery",
  CheckMail = "Check your email",
  SentLink = "We have sent a password reset link to email@email.com",
  ResendEmail = "Resend e-mail",
  BackTo = "Back to",
}
