export enum Login {
  Logo = "LOGO",
  Login = "Login",
  Username = "Username",
  Password = "Password",
  ForgotPassword = "  Forgot Password",
  OtherPlatform = " or login using other platforms",
  AlreadyAccount = "Already have an account?",
  Register = "Register",
  NewShopping = "Your new Shopping experience.",
  Google = " Login with Google",
  PhoneNumber = "Login with Phone Number",
  NoAccount = "Don’t have an account?",
  CreateAccount = "Create Account",
  VerificationCode = "We’ll send you a verification code you can use to Log in",
  PhoneNum = "Phone number",
  PasswordRecovery = "Password recovery",
  CheckMail = "Check your email",
  SentLink = "We have sent a password reset link to email@email.com",
  ResendEmail = "Resend e-mail",
  BackTo = "Back to",
  NewPassword = "New password",
  EnterNew = "Enter a new password for email@email.com",
  ConfirmNew = "Confirm New Password",
  MustContain = "Your password must contain",
  CapitalLetter = "At least one capital letter",
  LowerCaseLetter = "At least one lowercase letter",
  OneNum = "At least one number",
  Minimumcharacter = "Minimum character length is 8 characters",
  SetNew = "Set new password",
  PhoneVerification = "Phone Verification",
  EnterCode = "Enter the 6-digit code that we sent to =1234 567 899",
  DidNotReceive = "Didn’t receive code ?",
  Resend = "Resend",
  Verify = "Verify",
  Elevate = "Elevate Your Wardrobe with Trendy Styles !",
  Enheance = "Enhance your new shopping experience",
  VerifyOTP = "Verify OTP",
  Code = "Enter Verification Code",
  Email = "Email@gmail.com",
  GoBack = "Go back",
  TalkToUs = "Talk To Us",
  TalkToUsHeadline = "Fill in the form below, and we will get back to you as soon as possible!",
  Name = "Name",
  EmailAddress = "Email Address",
  Subject = "Subject",
  Details = "Details",
  SendMessage = "Send message",
}

export interface FormDetail {
  name: string;
  email: string;
  phoneNo: string;
  subject: string;
  details: string;
}
